services:
  bitcoin-visualizer:
    container_name: bitcoin-visualizer
    image: gq97a6/bitcoin-visualizer
    restart: unless-stopped
    ports:
      - 3000:3000
      - 443:443
    #volumes:
    #    - ./certs/key.pem:/app/certs/key.pem
    #    - ./certs/cert.pem:/app/certs/cert.pem
    environment:
      SERVER_PORT: 3000
      WEB_PORT: 443
      ZMQ_URI: tcp://localhost:28332
      RPC_URI: http://localhost:8332
      RPC_USERNAME: user
      RPC_PASSWORD: pass